runtime: custom
env: flex
# entrypoint: find ${VIRTUAL_ENV}/lib/python3.9/site-packages/streamlit -type f \( -iname \*.py -o -iname \*.js \) -print0 | xargs -0 sed -i 's/healthz/health-check/g' && streamlit run sim_v3.py --server.port $PORT --server.enableCORS=false

# runtime_config:
#   python_version: 3

entrypoint: streamlit run app.py --server.port $PORT
#
automatic_scaling:
   max_num_instances: 1
#
# network:
#   session_affinity: true
